### PR TITLE
Prepend hostname with WWW when subdomain is missing

### PR DESCRIPTION
**Pull request by Peleg**
and when `stripWWW` is `false`. Let me know if I'm overlooking anything :)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Why?

**Comment by Peleg** [comment]
@sindresorhus for url comparison (like in https://github.com/sindresorhus/compare-urls), `normalizeUrl('http://www.example.com', { stripWWW: false })` and `normalizeUrl('example.com', { stripWWW: false })` should probably yield the same result. I would have loved to just use `stripWWW`, but at my company we redirect example.com to www.example.com and it seems like an unnecessary step to add the `www` after just stripping it.

What are the issues with prepending `www` by default to naked domains?

**Comment by sindresorhus** [comment]
> What are the issues with prepending www by default to naked domains?

It's a subdomain, so it's not guaranteed to exist.

**Comment by Peleg** [comment]
Ugh, you're right. It's just so common that it seems odd to not have the option to assume they're the same w out stripping the www.

Defaulting to strip the www is also a compromise since www and the naked domain may point to two different things. 

Would you be open to adding an additional option to force www to naked domains?

**Comment by sindresorhus** [comment]
> Defaulting to strip the www is also a compromise since www and the naked domain may point to two different things.

True, but bare domains always point to something, in contrast.

> Would you be open to adding an additional option to force www to naked domains?

Not really. It doesn't make sense to apply it to random URLs. You can easily just add the `www` afterwards for your use-case.

**Pull request closed without merging**
