### PR TITLE
Add view-source support (#118)

### PR DESCRIPTION
**Pull request by iakgoog**

### CODE REVIEW

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/normalize-url/issues/118#issuecomment-687667546

Out of curiosity, how are you even ending up with `view-source:` URLs?

**Comment by iakgoog** [comment]
For example "view-source:view-source:view-source:view-source........." ?
Great, I'll fixed that

**Comment by sindresorhus** [comment]
@iakgoog That did not answer my question.

**Comment by iakgoog** [comment]
My apology. English is not native language.
I'm not sure if I understand your question correctly.
Are you asking me the reason why I decided to contribute to this issue @118?

**Comment by sindresorhus** [comment]
No, I'm asking you why you need this? Where are you encountering `view-source:` URLs?

**Comment by iakgoog** [comment]
nowhere except View page source on the browser

**Comment by sindresorhus** [comment]
So why do you need support for it in `normalize-url`? What's your use-case?

**Comment by iakgoog** [comment]
Just in case someone neeed it when they have a list of various kind or URLs to normalize.

**Comment by sindresorhus** [comment]
Sorry, I'm going to pass on this. I don't want to end up having to support an endless amount of non-standard protocols. And you have not presented an actual use-case or need for this.

**Comment by sindresorhus** [comment]
I already commented in https://github.com/sindresorhus/normalize-url/issues/118#issuecomment-687667546 that I welcome a pull request for a better error message, not an implementation for this.

**Comment by iakgoog** [comment]
That is acceptable.
Thank you for your time.

**Pull request closed without merging**
