### PR TITLE
Normalize encoding

### LINKED ISSUE #43: Normalize encoding
`file:///foo/node_modules/@angular/http` and `file:///foo/node_modules/%40angular/http` are equivalent, but `encodeURI` or `decodeURI` will do nothing to `@` or `%40`, while `encodeURIComponent`/`decodeURIComponent` will do. When for example saving URLs in a Map it is very important to always save and get a normalized form, it would be awesome if this module supported this.

### PR DESCRIPTION
**Pull request by Ricardo-Silva91**
Fixes #43:
'@' symbol not being decoded from '%40'
used the decodeURIComponent() method. Maybe it's too general but, since the code still passes all previous tests, I suppose it's preferable to just replacing the '@' character with str.replace(/%40/, '@'), as it can prevent future similar issues.

### CODE REVIEW

**Comment by stevenvachon** [comment]
`decodeURIComponent()` is not spec compliant and can result in issues. It might be best to wait to fix this along with the PR for #39.

**Comment by stevenvachon** [comment]
I just noticed something:
```
normalizeUrl('http://host/?var1=va%26lue&var2=value');
```
results in
```
http://host/?var1=va&lue&var2=value
```
which is a different URL.

**Comment by Ricardo-Silva91** [comment]
Hello again.
The latest commit has a fix for the bug @stevenvachon noticed (character '&' inside a parameter splits the parameter in 2).
With this hotfix, the complexity of the function increased to 23, not sure if that's a problem.
I also added a test for the bug.

**Comment by sindresorhus** [comment]
Closing as we no longer decode the URL.

**Pull request closed without merging**
