### PR TITLE
Check if pathname is empty or not

### PR DESCRIPTION
**Pull request by batjaa**
When you pass an URL with empty pathname it was causing URL object to throw a bug.
`http://` should resolve to `http://`

### CODE REVIEW

**Comment by batjaa** [comment]
Actually not sure to what it should resolve to. It's not stated in that wiki article. An empty string might make more sense, too. Let me know.

**Comment by kevva** [comment]
What's the use case for this? I'm all for preventing unexpected errors for users, but in this case it almost feels like the check should happen before this module. `http://` is not even an URL.

**Comment by batjaa** [comment]
One use case would be if you may want to use the normalizer for showing a placeholder for an input, like 

image

**Comment by sindresorhus** [comment]
I think it should throw. It's not a valid URL. This is a slippery slope. Soon we'll get issues about `🦄` not normalizing to `🐴` :p

**Comment by sindresorhus** [comment]
@batjaa Can you update the pull request?

**Pull request merged**
