### PR TITLE
Enable real browser test

### PR DESCRIPTION
**Pull request by loynoir**
### Users
There are two ways if you want to test version >= 7.0.0 in real browser,

1. git clone then visit [browser-test/index.html](browser-test/index.html)
2. Zero install using rawgit, [link](https://ghcdn.rawgit.org/loynoir/normalize-url/0fd8bf27b3400d4cf67bce6072c3f34efa8f4e56/browser-test/index.html). Remember to change hash to latest commit.

### Changes
- [source] Change `/JsRegexpLookbehind/` to `new RegExp(JsRegexpLookbehind)`, prevent syntax error breaks user code.
- [source] Use `reverse-lookahead-reverse` as fallback when not support `JsRegexpLookbehind`.
- [source] Add URLSearchParameters.sort ponyfill as fallback.
- [source] Add options `preferJsRegexpLookbehind` and `preferURLSearchParamsSort` to run fallback logic in modern runtime.
- [types] Add above two options to `.d.ts`.
- [source] Move `normalizeUrl(options)` options validation to most top.
- [source] Treat custom protocol as .defaultProtocol, to prevent host as part of pathname.
- [source] Change back custom protocol after `urlObject.toString`, to prevent pathname changed again.
- [workflow] Add karma to enable automate headless browser tests.
- [workflow] Add rollup to transform `regexp named-capturing-groups` and bundle tests for browser.
- [tests] Change `ava` to `mocha+chai`, enable to test it in Node.js / Headless Chrome / Headless Firefox / Any real browsr.
- [tests] Update prev `invalid urls` to match more than Node.js env.
- [tests] Seperate some long tests in to small parts to easy identify problems.

### Test Status
(32/32) Test passed with
- Node.js 14
- Chrome headless driver
- Firefox headless driver
- Chrome 92
- Firefox 90
- Firefox 68 ESR
- Opera59
- Yandex 7 (2017)

### CODE REVIEW

**Comment by loynoir** [comment]
https://github.com/sindresorhus/normalize-url/issues/105

**Comment by sindresorhus** [comment]
Safari support was fixed in https://github.com/sindresorhus/normalize-url/releases/tag/v7.0.1. I'm not interested in browser tests, browser-specific options, or the `.sort` polyfill. You also have way too many unrelated changes in a single pull request.

**Comment by loynoir** [comment]
Hi, @sindresorhus 

> I'm not interested in browser tests
But how can you guarantee this library works in browser, without testing it in browser?

Eg: issue#147

> browser-specific options
I know that you may not like that option, so I did try to remove it.
But test-runtime is modern, need to way to run all logic.
So I restore them.

> You also have way too many unrelated changes in a single pull request
I'm kind of non professional newbie.
Should I combine all commits as one, and break them into small features.
Then `one feature -> contribute -> one feature -> contribute`?

**Comment by loynoir** [comment]
FYI, there are something I found so far.
1.  some rare url in browser, issue#147
_Fixed in my latest fork_
2. name capture group may break ok code like issues#105
https://github.com/sindresorhus/normalize-url/blob/24560330a31eda9253172c02339ec610f5917d4b/index.js#L8
3. options validate should ASAP
https://github.com/sindresorhus/normalize-url/blob/24560330a31eda9253172c02339ec610f5917d4b/index.js#L105

Have a nice day @sindresorhus 😊

**Comment by sindresorhus** [comment]
> But how can you guarantee this library works in browser, without testing it in browser?

I never made it for the browser.

**Comment by sindresorhus** [comment]
> options validate should ASAP

Not sure what you mean?

**Comment by sindresorhus** [comment]
Old browser support is not a concern for this package. It's up to you to use Babel and polyfill if you need to use it in older browsers. I only merged the Safari fix as it applies to latest Safari.

**Comment by loynoir** [comment]
> > In modern and old browser, custom protocol error like issue#147
> 
> #132

Not sure for that pull, but existing today-`test.js` failed for both modern and old browser issue#147

**Comment by loynoir** [comment]
> > options validate should ASAP
> 
> Not sure what you mean?


```js
 function normalizeUrl(urlString, options) {
 // ...code
	if (options.forceHttp && options.forceHttps) {
		throw new Error('The `forceHttp` and `forceHttps` options cannot be used together');
	}
// ...code
}


 function normalizeUrl(urlString, options) {
	if (options.forceHttp && options.forceHttps) {
		throw new Error('The `forceHttp` and `forceHttps` options cannot be used together');
	}
 // ...code
// ...code
}
```

**Comment by loynoir** [comment]
> > But how can you guarantee this library works in browser, without testing it in browser?
> 
> I never made it for the browser. But it doesn't use anything specific to Node.js, so if it works in Node.js, it should work in modern browsers too.

But your "this child" seems to be also used in browser from recent issues?
Maybe consider using convert `ava` to `mocha+chai+karma`?
As it also provide automate browser test ability for headless browser drivers?

**Comment by sindresorhus** [comment]
I'm not interested in browser testing.

**Comment by loynoir** [comment]
> But it doesn't use anything specific to Node.js, so if it works in Node.js, it should work in modern browsers too.

`URL` implement is different. When custom protocol, node behavior is `whatwg-url`, 
but browser is not, `A://B/C` host in browser is empty.

**Comment by loynoir** [comment]
> I'm not interested in browser testing.

But I saw issues related to browser, may it give a try, decrease future potential issues?
As it can be **automated**?

**Pull request closed without merging**
